### ISSUE TITLE
Same beta for all of the heads

### ISSUE THREAD

**Issue by zukowskanina** [vmarinowski/infini-attention#4]
Hi! First of all, thank you very much for your contribution! The code you provided is of high quality and is very readable.

However, one thing bugs me. It seems like the beta parameter is a single scalar for all heads, whereas in the paper they use a separate beta for each head.

Quoting: '''Long-term context injection. We aggregate the local attention state Adot and memory
retrieved content Amem via a learned gating scalar β:
A = sigmoid(β) ⊙ Amem + (1 − sigmoid(β)) ⊙ Adot. (6)
This adds only a single scalar value as training parameter per head while allowing a
learnable trade-off between the long-term and local information flows in the model (Wu
et al., 2022)'''

Thank you so much:)

**Comment by vmarinowski** [comment]
Hello, they were so unclear about how to choose and initialize beta, so I was trying to figure it out on my own. I used same beta value for all heads and it worked actually very well. So, I didn't touch it. xD
