### ISSUE TITLE
Regarding implementation

### ISSUE THREAD

**Issue by qmin2** [vmarinowski/infini-attention#5]
In infini_attention.py forward() function,  

There is `query = query.view(batch_size, self.n_head, self.n_segments, self.seq_len // self.n_segments, self.d_head)`
the above code line is intended to reshape the tensor from [batch_size, seq_len, dim] to [batch_size, n_head, n_seqments, seq_len // n_segment, d_head].

But I think this operation might  mixe up the tensor dimensions
Wouldn't it be more appropriate to reshape the tensor as follows?
 `query.view(batch_size,  n_seqments, seq_len // n_segment, n_head, d_head)`
(I'm not sure and I could be wrong)

**Comment by vmarinowski** [comment]
Hello, yes you are right! I will change it, thanks.
